version: '3.9'

services:
  text-classifier-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: text-classifier-api
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - ENV=production
    volumes:
      - .:/app