TrainingArguments:
  output_dir: "./results"
  eval_strategy: "epoch"
  learning_rate: 5e-5
  per_device_train_batch_size: 16
  num_train_epochs: 3
  weight_decay: 0.01
  logging_dir: "./logs"
  logging_steps: 10